export const TYPE_COLORS = {
  normal: '#A8A878',
  fire: '#F08030',
  water: '#6890F0',
  grass: '#78C850',
  electric: '#F8D030',
  ice: '#98D8D8',
  fighting: '#C03028',
  poison: '#A040A0',
  ground: '#E0C068',
  flying: '#A890F0',
  psychic: '#F85888',
  bug: '#A8B820',
  rock: '#B8A038',
  ghost: '#705898',
  dragon: '#7038F8',
  dark: '#705848',
  steel: '#B8B8D0',
  fairy: '#EE99AC',
}

export const STARTERS = [
  { id: 1, name: 'Bisasam', apiName: 'bulbasaur' },
  { id: 4, name: 'Glumanda', apiName: 'charmander' },
  { id: 7, name: 'Schiggy', apiName: 'squirtle' },
]

export const GYMS = [
  {
    id: 1,
    name: 'Variablen & Typen',
    leader: 'Rocko',
    leaderEN: 'Brock',
    type: 'rock',
    badge: 'Felsorden',
    pokemonRewards: [74, 95, 56],
    leaderPokemon: [74, 95],
    description: 'Lerne die Grundlagen: Variablen, Datentypen und einfache Operationen.',
  },
  {
    id: 2,
    name: 'Funktionen & Scope',
    leader: 'Misty',
    leaderEN: 'Misty',
    type: 'water',
    badge: 'Quellorden',
    pokemonRewards: [120, 121, 54],
    leaderPokemon: [120, 121],
    description: 'Meistere Funktionen, Parameter, Rueckgabewerte und Scope.',
  },
  {
    id: 3,
    name: 'Arrays & Objekte',
    leader: 'Major Bob',
    leaderEN: 'Lt. Surge',
    type: 'electric',
    badge: 'Donnerorden',
    pokemonRewards: [100, 25, 81],
    leaderPokemon: [100, 26],
    description: 'Arbeite mit Arrays, Objekten und deren Methoden.',
  },
  {
    id: 4,
    name: 'Async & Promises',
    leader: 'Erika',
    leaderEN: 'Erika',
    type: 'grass',
    badge: 'Farborden',
    pokemonRewards: [43, 69, 114],
    leaderPokemon: [71, 45],
    description: 'Verstehe asynchronen Code, Promises und async/await.',
  },
  {
    id: 5,
    name: 'React Components',
    leader: 'Koga',
    leaderEN: 'Koga',
    type: 'poison',
    badge: 'Seelenorden',
    pokemonRewards: [88, 109, 89],
    leaderPokemon: [110, 89],
    description: 'Baue deine ersten React-Komponenten mit JSX und Props.',
  },
  {
    id: 6,
    name: 'State & Events',
    leader: 'Sabrina',
    leaderEN: 'Sabrina',
    type: 'psychic',
    badge: 'Sumpforden',
    pokemonRewards: [63, 64, 122],
    leaderPokemon: [65, 122],
    description: 'Lerne useState, Event-Handler und kontrollierte Komponenten.',
  },
  {
    id: 7,
    name: 'useEffect & API',
    leader: 'Pyro',
    leaderEN: 'Blaine',
    type: 'fire',
    badge: 'Vulkanorden',
    pokemonRewards: [58, 77, 59],
    leaderPokemon: [59, 78],
    description: 'Nutze useEffect fuer Side-Effects und API-Aufrufe.',
  },
  {
    id: 8,
    name: 'Komplette App',
    leader: 'Giovanni',
    leaderEN: 'Giovanni',
    type: 'ground',
    badge: 'Erdorden',
    pokemonRewards: [112, 34, 51],
    leaderPokemon: [112, 34],
    description: 'Die Elite Four! Baue eine vollstaendige React-Anwendung.',
  },
]
